x-app: &app
  build:
    context: watercrawl
    dockerfile: Dockerfile
    args:
      - WATER_CRAWL_BACKEND_IMAGE
  env_file:
    - app.env
  volumes:
    - storage_volume:/var/www/storage
  depends_on:
    - postgres
    # - minio
    
services:
  app:
    <<: *app
    restart: always

    command: gunicorn -b 0.0.0.0:9000 -w 2 watercrawl.wsgi:application --access-logfile - --error-logfile - --timeout 3600
    
  celery:
    <<: *app
    restart: always
    command: celery -A watercrawl worker -B -l info --statedb=.celery/worker.state

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - WATER_CRAWL_FRONTEND_IMAGE
    restart: always
    env_file:
      - frontend.env

  nginx:
    image: ${NEGINX_IMAGE:-nginx:1.25-alpine}
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - storage_volume:/var/www/storage
    depends_on:
      - frontend
      - app

  # minio:
  #   image: {MINIO_IMAGE:-minio/minio:RELEASE.2024-11-07T00-52-20Z}
  #   restart: always
  #   volumes:
  #     - minio-data:/data
  #   command: server /data --console-address ":9001"
  #   env_file:
  #     - minio.env
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:9001/minio/health/live"]
  #     interval: 30s
  #     timeout: 20s

  postgres:
    image: ${POSTGRES_IMAGE:-postgres:17.2-alpine3.21}
    restart: always
    env_file:
      - db.env
    volumes:
      - postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s

  playwright:
    image: ${PLAYWRIGHT_IMAGE:-watercrawl/playwright:1.1}
    restart: always
    env_file:
      - playwright.env

  redis:
    image: ${REDIS_IMAGE:-redis:7.2-alpine}
    restart: always
    volumes:
      - redis-data:/data

volumes:
  postgres-db:
  # minio-data:
  storage_volume:
  redis-data: